[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (output of build)
  publish = "dist"
  
  # Directory with the build files
  base = "."

[build.environment]
  # Node version for builds
  NODE_VERSION = "18"
  
  # npm version
  NPM_VERSION = "9"

# Redirect rules for SPA and SEO
[[redirects]]
  # Redirect www to non-www (if needed)
  from = "https://www.guildsnglory.com/*"
  to = "https://guildsnglory.com/:splat"
  status = 301
  force = false

[[redirects]]
  # Handle newsletter subscription redirects
  from = "/subscribe"
  to = "/subscribe.html"
  status = 200

[[redirects]]
  # Handle thank you page redirects  
  from = "/thankyou"
  to = "/thankyou.html"
  status = 200

[[redirects]]
  # Fallback for any other routes to homepage
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for assets
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/img/*"
  [headers.values]
    # Longer cache for images
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    # Cache CSS files
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    # Cache JavaScript files
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    # Cache fonts for a year
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling for newsletter subscription
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Branch deploy settings
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
  buildDir = "dist"